### ISSUE TITLE
ant-launcher?

### ISSUE THREAD

**Issue by mattkoch614** [HL7/genomics-reporting#1]
@lmckenzi Can you shed some light on what https://github.com/HL7/genomics-reporting/blob/master/framework/ant/ant-launcher.jar is used for? I see it is executed from the scripts in the root directory - I am assuming it pulls down the HL7 publishing tool, perhaps a few other things?

**Comment by lmckenzi** [comment]
It pre-processes the IG file to deal with spreadsheet processing, it creates the artifacts index and does a few other things.  You always need to run it before checking in content as the IG-publisher doesn't (yet) know how to run the ant script itself.  That should change sometime in the next 3-4 months.
